### ISSUE TITLE
Research: Best OCR API

### ISSUE THREAD

**Issue by Tlaka95** [Tlaka95/COS301_TECH_TITANS_TEAM#12]

**Comment by DarKnight3** [comment]
http://docs.mathpix.com

Mathpix is an API OCR designed to read images that contain Math!
![0gcjhspr5g3y](https://cloud.githubusercontent.com/assets/25769574/26015133/e3fa72b6-375f-11e7-80ff-c0d704bcbf3f.gif)
![mathpix](https://cloud.githubusercontent.com/assets/25769574/26015134/e42f7e16-375f-11e7-887f-acffcc361731.png)
