### ISSUE TITLE
Caracal: Deployment Diagram

### ISSUE THREAD

**Issue by Tlaka95** [Tlaka95/COS301_TECH_TITANS_TEAM#16]

**Comment by Tlaka95** [comment]
@Oratile-15306195  and @DarKnight3 , this is the deployment Diagram for the Caracal project. Please Review it ASAP and get back to me if any changes are required

**Comment by Oratile-15306195** [comment]
Since we do not have to add technologies inside the Deployment Diagram, I think it's fine.
